site_name: TorQ
site_favicon: graphics/favicon.ico
nav:
    - Home: index.md
    - About: Overview.md
    - Cheat Sheat: cheatsheet.md
    - Getting Started: gettingstarted.md
    - Installation: InstallGuide.md
    - Utilities: utilities.md
    - Handlers: handlers.md
    - Connection Management: conn.md
    - Processes: Processes.md
    - Analytics Library: analyticslib.md 
    - Data Access Library: dataaccess.md
    - Monitoring: monit.md 
    - Visualisation: visualisation.md
    - Testing: unittesting.md
    - TorQ Blog Posts: blog.md
copyright: Copyright &copy 2020 Data Intellect Limited.  Kx &reg and kdb+ are registered trademarks of Kx Systems Inc.

theme: material
repo_name: GitHub
repo_url: https://github.com/AquaQAnalytics/TorQ
extra:
   logo: graphics/DataIntellect-TorQ-logo.png
   palette:
      primary: indigo
      accent: green
   social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/AquaQAnalytics
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/data_intellect
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/company/data-intellect-challenge-accepted
   analytics:
      provider: google
      property: UA-51911331-4
